server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_6b4b7451a995
    token: lyz1010

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

























